In [2]:
# !pip install transformers

In [5]:
from transformers import BertTokenizer, BertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained("bert-base-uncased")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [13]:
text = "Replace me by any text you'd like."
encoded_input = tokenizer.tokenize(text)
for token in encoded_input: 
    print(f"{token} , Token ID : {tokenizer.convert_tokens_to_ids(token)}")
# output = model(**encoded_input)

replace , Token ID : 5672
me , Token ID : 2033
by , Token ID : 2011
any , Token ID : 2151
text , Token ID : 3793
you , Token ID : 2017
' , Token ID : 1005
d , Token ID : 1040
like , Token ID : 2066
. , Token ID : 1012


In [14]:
text = "play foot-ball."
encoded_input = tokenizer.tokenize(text)
for token in encoded_input: 
    print(f"{token} , Token ID : {tokenizer.convert_tokens_to_ids(token)}")

play , Token ID : 2377
foot , Token ID : 3329
- , Token ID : 1011
ball , Token ID : 3608
. , Token ID : 1012


In [15]:
text = "play foottt-ball."
encoded_input = tokenizer.tokenize(text)
for token in encoded_input: 
    print(f"{token} , Token ID : {tokenizer.convert_tokens_to_ids(token)}")

play , Token ID : 2377
foot , Token ID : 3329
##tt , Token ID : 4779
- , Token ID : 1011
ball , Token ID : 3608
. , Token ID : 1012


In [17]:
tokenizer(text,return_tensors="pt")

{'input_ids': tensor([[ 101, 2377, 3329, 4779, 1011, 3608, 1012,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}

In [48]:
ptokens = tokenizer(text,return_tensors="pt")

ptokens_ids = ptokens['input_ids']


ptokens

{'input_ids': tensor([[ 101, 2377, 3329, 4779, 1011, 3608, 1012,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}

In [35]:
ttokens = tokenizer(text,return_tensors="tf")['input_ids']
ttokens

<tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[ 101, 2377, 3329, 4779, 1011, 3608, 1012,  102]])>

In [36]:
ttokens

<tf.Tensor: shape=(1, 8), dtype=int32, numpy=array([[ 101, 2377, 3329, 4779, 1011, 3608, 1012,  102]])>

In [38]:
tokenizer.convert_ids_to_tokens(ptokens_ids[0])

['[CLS]', 'play', 'foot', '##tt', '-', 'ball', '.', '[SEP]']

In [39]:
tokenizer.convert_ids_to_tokens(ttokens[0])

['[CLS]', 'play', 'foot', '##tt', '-', 'ball', '.', '[SEP]']

In [52]:
out1 = model(ptokens_ids)
out1
# len(out1[][1])

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[-0.0973,  0.0348, -0.1640,  ..., -0.1981,  0.1242,  0.7169],
         [ 0.5311,  0.0539,  0.0021,  ..., -0.1574,  0.5985,  0.0440],
         [ 0.4011, -0.3905,  0.3016,  ..., -0.0181,  0.0029, -0.9020],
         ...,
         [-0.0215, -0.8562,  0.2143,  ...,  0.0302, -0.3039, -0.0671],
         [-0.1902, -0.3608, -0.4653,  ...,  0.2061,  0.1218, -0.0703],
         [ 0.8401,  0.3220, -0.3806,  ...,  0.2678, -0.7167, -0.1093]]],
       grad_fn=<NativeLayerNormBackward0>), pooler_output=tensor([[-8.6771e-01, -3.8209e-01, -9.1238e-01,  8.2578e-01,  8.2466e-01,
         -7.1584e-02,  8.6921e-01,  2.8143e-01, -7.3891e-01, -9.9999e-01,
         -5.6085e-01,  8.1962e-01,  9.8088e-01,  5.4753e-01,  9.0938e-01,
         -6.0601e-01, -1.4964e-01, -6.3724e-01,  2.4774e-01, -3.4570e-01,
          6.9014e-01,  9.9999e-01, -1.1031e-01,  2.7855e-01,  4.3415e-01,
          9.6832e-01, -6.9090e-01,  9.1802e-01,  9.5257e-01,  7.122

In [55]:
len(out1['last_hidden_state'][0][0])

768

In [93]:
# tokenizer.encode(out1['last_hidden_state'][0][:])

In [94]:
sentence1 = "I will play football this moring"
sentence2 = "We are going to the theater  to watch a play"
word = "play"
tokens1 = tokenizer(sentence1,return_tensors="pt")
tokens2 = tokenizer(sentence2,return_tensors="pt")

tokens1_ids = tokens1['input_ids']
tokens2_ids = tokens2['input_ids']


tokens1_ids,tokens2_ids

(tensor([[  101,  1045,  2097,  2377,  2374,  2023, 22993,  3070,   102]]),
 tensor([[ 101, 2057, 2024, 2183, 2000, 1996, 4258, 2000, 3422, 1037, 2377,  102]]))

In [95]:
import numpy as np
word_id = tokenizer.convert_tokens_to_ids(word)

word_id

2377

In [96]:
word_in_sentence1 = np.where(tokens1_ids == word_id)[1]
word_in_sentence2 = np.where(tokens2_ids == word_id)[1]

word_in_sentence1,word_in_sentence2

(array([3], dtype=int64), array([10], dtype=int64))

In [97]:
out1 = model(**tokens1)
out2 = model(**tokens2)

In [98]:
embedding_1 = out1['last_hidden_state'][0].detach().numpy()
embedding_2=  out2['last_hidden_state'][0].detach().numpy()

In [99]:
word1 = embedding_1[word_in_sentence1][0]

In [100]:
word2 = embedding_2[word_in_sentence2][0]

In [101]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity([word1],[word2])

array([[0.47865653]], dtype=float32)